[package]
name = "pinkytwirl"
version = "0.1.0"
edition = "2021"

[lib]
name = "pinkytwirl"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[build-dependencies]
cbindgen = "0.24"