#include <stdint.h>
#include <stdbool.h>


/* Warning: This file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct pinkytwirl_PinkyTwirlEngine pinkytwirl_PinkyTwirlEngine;

typedef struct pinkytwirl_FFIKeyEvent {
  char *key;
  bool state;
  bool shift;
  bool ctrl;
  bool alt;
  bool meta;
} pinkytwirl_FFIKeyEvent;

struct pinkytwirl_PinkyTwirlEngine *pinkytwirl_engine_new(const char *config_path);

void pinkytwirl_engine_free(struct pinkytwirl_PinkyTwirlEngine *ptr);

struct pinkytwirl_FFIKeyEvent *pinkytwirl_engine_handle_key_event(struct pinkytwirl_PinkyTwirlEngine *engine,
                                                                  uint16_t key_code,
                                                                  bool down,
                                                                  bool shift,
                                                                  bool ctrl,
                                                                  bool option,
                                                                  bool meta,
                                                                  const char *app_name,
                                                                  const char *window_name,
                                                                  uintptr_t *out_length);

void pinkytwirl_free_key_events(struct pinkytwirl_FFIKeyEvent *events, uintptr_t length);
